
compiler = ghc
options = -v1

all:
	$(compiler) $(options) --make Main.hs
	$(compiler) $(options) --make Main.hs

clean:
	rm -f *~
	rm -f */*~
	rm -f */*/*~
	rm -f */*/*/*~
	rm -f *.o
	rm -f */*.o
	rm -f */*/*.o
	rm -f */*/*/*.o
	rm -f *.hi
	rm -f */*.hi
	rm -f */*/*.hi
	rm -f */*/*/*.hi


